/**
 * CDS Platform error code taxonomy.
 * Prefix determines category:
 *   VAL_* — Validation errors (400)
 *   AUTH_* — Authentication/Authorization (401/403)
 *   BIZ_* — Business rule violations (409/422)
 *   SYS_* — System errors (500/503)
 *
 * @see docs/domain-model/api-contracts.ts
 */
export const ErrorCode = {
  // --- Validation (400) ---
  VAL_REQUIRED_FIELD: 'VAL_REQUIRED_FIELD',
  VAL_INVALID_FORMAT: 'VAL_INVALID_FORMAT',
  VAL_OUT_OF_RANGE: 'VAL_OUT_OF_RANGE',
  VAL_INVALID_ENUM: 'VAL_INVALID_ENUM',
  VAL_INVALID_UUID: 'VAL_INVALID_UUID',

  // --- Authentication / Authorization (401/403) ---
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_INSUFFICIENT_ROLE: 'AUTH_INSUFFICIENT_ROLE',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',

  // --- Business Rules (409/422) ---
  BIZ_DEMAND_NOT_BIDDABLE: 'BIZ_DEMAND_NOT_BIDDABLE',
  BIZ_OFFER_ALREADY_ACCEPTED: 'BIZ_OFFER_ALREADY_ACCEPTED',
  BIZ_PROVIDER_NOT_ACTIVE: 'BIZ_PROVIDER_NOT_ACTIVE',
  BIZ_CONTRACT_NOT_SIGNABLE: 'BIZ_CONTRACT_NOT_SIGNABLE',
  BIZ_PAYMENT_ALREADY_COMPLETED: 'BIZ_PAYMENT_ALREADY_COMPLETED',
  BIZ_REVIEW_ALREADY_EXISTS: 'BIZ_REVIEW_ALREADY_EXISTS',
  BIZ_DEPOSIT_REQUIRED: 'BIZ_DEPOSIT_REQUIRED',
  BIZ_DUPLICATE_OFFER: 'BIZ_DUPLICATE_OFFER',
  BIZ_DEMAND_EXPIRED: 'BIZ_DEMAND_EXPIRED',
  BIZ_INVALID_STATUS_TRANSITION: 'BIZ_INVALID_STATUS_TRANSITION',

  // --- Not Found (404) ---
  NOT_FOUND: 'NOT_FOUND',

  // --- System (500/503) ---
  SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
  SYS_DATABASE_ERROR: 'SYS_DATABASE_ERROR',
  SYS_EXTERNAL_SERVICE: 'SYS_EXTERNAL_SERVICE',
  SYS_RATE_LIMIT: 'SYS_RATE_LIMIT',
  SYS_SERVICE_UNAVAILABLE: 'SYS_SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
